/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Muril
 */
public class Menu_Saneamento extends javax.swing.JFrame {

    private Reporte Reporte;
    private Lista Lista;
    private Marcar Marcar;

    /**
     * Creates new form Menu_Saneamento
     */
    public Menu_Saneamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuLa = new javax.swing.JLabel();
        ReportarBotão = new javax.swing.JButton();
        ListarBotão = new javax.swing.JButton();
        MarcarBotão = new javax.swing.JButton();
        SairBotão = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuLa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MenuLa.setText("Menu");

        ReportarBotão.setText("Reportar denúncia");
        ReportarBotão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportarBotãoActionPerformed(evt);
            }
        });

        ListarBotão.setText("Listar denúncias");
        ListarBotão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarBotãoActionPerformed(evt);
            }
        });

        MarcarBotão.setText("Marcar denúncia como resolvida");
        MarcarBotão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcarBotãoActionPerformed(evt);
            }
        });

        SairBotão.setText("Sair");
        SairBotão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairBotãoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(MenuLa)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MarcarBotão, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListarBotão, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SairBotão, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReportarBotão, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(MenuLa)
                .addGap(41, 41, 41)
                .addComponent(ReportarBotão)
                .addGap(18, 18, 18)
                .addComponent(ListarBotão)
                .addGap(18, 18, 18)
                .addComponent(MarcarBotão)
                .addGap(18, 18, 18)
                .addComponent(SairBotão)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReportarBotãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportarBotãoActionPerformed

    Reporte= new Reporte();
        this.dispose();
        Reporte.setVisible(true);
       
    
    }//GEN-LAST:event_ReportarBotãoActionPerformed

    private void ListarBotãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarBotãoActionPerformed
        // TODO add your handling code here:
        Lista = new Lista();
        this.dispose();
        Lista.setVisible(true);
    }//GEN-LAST:event_ListarBotãoActionPerformed

    private void MarcarBotãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcarBotãoActionPerformed
        // TODO add your handling code here:
        Marcar = new Marcar();
        this.dispose();
        Marcar.setVisible(true);
    }//GEN-LAST:event_MarcarBotãoActionPerformed

    private void SairBotãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairBotãoActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_SairBotãoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {  /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Saneamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Saneamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Saneamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Saneamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 } catch (ExceptionInInitializerError e) {
        e.printStackTrace();
    }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Saneamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ListarBotão;
    private javax.swing.JButton MarcarBotão;
    private javax.swing.JLabel MenuLa;
    private javax.swing.JButton ReportarBotão;
    private javax.swing.JButton SairBotão;
    // End of variables declaration//GEN-END:variables
}